services:

  db:
    container_name: db
    # match prod
    image: mariadb:10.11.6
    hostname: mysql
    volumes:
      - ./.docker/mysql/:/var/lib/mysql-docker/

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
      MYSQL_USER: weather
      MYSQL_PASSWORD: weather
      # settings needed for toad support
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4
    ports:
      - 3306:3306
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--password=root"]
      interval: 1m30s
      timeout: 60s
      retries: 6
