[project]
version = "0.1"
name = "WeatherWatch"
description = "weather watch sensor processor"
readme = "README.md"
authors = [
    {name = "tim Cronin", email = "tecronin@gmail.com"},
]
dependencies = [
    "setuptools",
    "black",
    "coverage",
    "isort",
    "flake8",
    "Flake8-pyproject",         
    "PyYAML",
    "pyaml-env",
    "SQLAlchemy",
    "mariadb",
    "adafruit-circuitpython-bmp3xx",
    "apscheduler",
    "python-event-bus",
    "py-singleton",
    "psutil",
    "lgpio",
    "numpy",
    "pylint",
    "pylint-report"
]
requires-python = ">=3.11"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128
target-version = ["py312"]
#include = "\.pyi?$"
#"extend-exclude" excludes files or directories in addition to the defaults
#extend-exclude = """
## A regex preceded with ^/ will apply only to files and directories
## in the root of the project.
#(
#  ^/foo.py    # exclude a file named foo.py in the root of the project
#  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
#)
#"""

# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
py_version = 312
profile = "black"
line_length = 128
remove_redundant_aliases = true
# TODO 
#formatter = "black"
skip = [".gitignore", ".dockerignore"]

[tool.flake8]
max-line-length = 128
max-complexity = 18

[tool.pylint.MASTER]
load-plugins = "pylint_report"

[tool.pylint.REPORTS]
output-format = "pylint_report.CustomJsonReporter"

[tool.pylint."MESSAGES CONTROL"]
disable = '''C0103,
'''
output-format = "json"