version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    verbose:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: verbose
        stream: ext://sys.stdout
loggers:
    root:
        level: DEBUG
        handlers: [console]