version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s|%(pathname)s:%(lineno)d|%(levelname)s- %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: '{path}/weather.log'
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

loggers:
    root:
        level: DEBUG
        handlers: [console, file]