version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s|%(filename)s:%(lineno)d|%(levelname)s- %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: !ENV ${WW_LOG_LEVEL:DEBUG}
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: !ENV ${WW_LOG_LEVEL:DEBUG}
        formatter: simple
        filename: !ENV ${WW_LOG_PATH:.}/${WW_LOG_NAME:WeatherWatch}.log
        maxBytes: 2097152 # 2MB
        backupCount: 10
        encoding: utf8

loggers:
    root:
        level: !ENV ${WW_LOG_LEVEL:DEBUG}
        handlers: [console, file]
    # dash app spewing debug    
    watchdog.observers.inotify_buffer:
        level: INFO
