version: 1
disable_existing_loggers: no
formatters:
    simple:
        format: "%(asctime)s|%(pathname)s:%(lineno)d|%(levelname)s- %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
loggers:
    root:
        level: DEBUG
        handlers: [console]