database:
  dialect: !ENV ${WW_DB_DIALECT:mysql}
  driver: !ENV ${WW_DB_DRIVER:mysqlconnector}
  host: !ENV ${WW_DB_HOST:localhost}
  port: !ENV ${WW_PORT:3306}
  name: !ENV ${WW_DB_NAME:weather}
  username: !ENV ${WW_DB_USERNAME}
  password: !ENV ${WW_DB_PASSWORD}
bmp:
  388:
    i2caddr: 0x77
  280:
    i2caddr: 0x76  
sdr:
  reader:
    timeout: !ENV ${WW_SENSOR_READ_TIMEOUT:90}
  sensors:
      - name: outdoor
        model: Cotech-367959 
        id: 96
        dataClass: OutdoorData
        device: 153
      - name: indoor_3dfloor   
        model: Ambientweather-F007TH 
        id: 192 
        channel: 2 
        dataClass: IndoorData
        device: 20
      - name: indoor_basement   
        model: Ambientweather-F007TH 
        id: 95 
        channel: 3 
        dataClass: IndoorData
        device: 20
scheduler:
  sensor:
    interval: !ENV ${WW_SENSOR_INTERVAL:5}