version: 1.1.0
aqi:
  enable: !ENV tag:yaml.org,2002:bool ${WW_AQI_ENABLE:true}
camera:
  enable: !ENV tag:yaml.org,2002:bool ${WW_CAM_ENABLE:true}
  folder: !ENV ${WW_CAM_FOLDER:pix}
  extension: !ENV ${WW_CAM_FILE_EXT:.jpg}
  tuning:
    enable: !ENV tag:yaml.org,2002:bool ${WW_CAM_TUNE_ENABLE:true}
    file: !ENV ${WW_CAM_TUNE_FILE:imx708_noir.json}
# dashboard app
dashboard:
  # listen host
  host: !ENV ${WW_DASH_HOST:0.0.0.0}
  # listen port
  port: !ENV tag:yaml.org,2002:int ${WW_DASH_PORT:8000}
  debug: !ENV tag:yaml.org,2002:bool ${WW_DASH_DEBUG:true}
database:
  dialect: !ENV ${WW_DB_DIALECT:mariadb}
  driver: !ENV ${WW_DB_DRIVER:mariadbconnector}
  host: !ENV ${WW_DB_HOST:127.0.0.1}
  port: !ENV tag:yaml.org,2002:int ${WW_PORT:3306}
  name: !ENV ${WW_DB_NAME:weather}
  username: !ENV ${WW_DB_USERNAME}
  password: !ENV ${WW_DB_PASSWORD}
  pool:
    size: 3
    overflow: 3
scheduler:
  aqi:
    # air quality sensor interval
    interval: !ENV tag:yaml.org,2002:int ${WW_AQI_INTERVAL:15}
  camera:
    # camera pic interval should not be < 5. can eat up disk space
    interval: !ENV tag:yaml.org,2002:int ${WW_CAMERA_INTERVAL:5}
  pimetrics:
    # sensystem metrics polling for looking for resource issues
    interval: !ENV tag:yaml.org,2002:int ${WW_PIMETRICS_INTERVAL:10}
  sensor:
    # sensor polling interval should not be < 5
    interval: !ENV tag:yaml.org,2002:int ${WW_SENSOR_INTERVAL:5}
sdr:
  reader:
    # this is the total time the reader will poll if not all sensors are read
    timeout: !ENV tag:yaml.org,2002:int ${WW_SENSOR_READ_TIMEOUT:240}
  sensors:
      # doing device reset of outdoor sensor will change the id
      # device is the 
      - name: outdoor
        # rtl_433 model (might not match actual sensor) 
        model: Cotech-367959 
        id: !ENV tag:yaml.org,2002:int ${WW_OUT_SENSOR_ID:30}
        # class that will process the data from raw json
        dataClass: OutdoorData
        # rtl_433 device id
        device: 153
      - name: indoor_3dfloor   
        model: Ambientweather-F007TH 
        id: 192 
        channel: 2 
        dataClass: IndoorData
        device: 20
      - name: indoor_basement   
        model: Ambientweather-F007TH 
        id: 95 
        channel: 3 
        dataClass: IndoorData
        device: 20
