version: 1.1.0
aqi:
  enable: !ENV tag:yaml.org,2002:bool ${WW_AQI_ENABLE:true}
  retry: !ENV tag:yaml.org,2002:int ${WW_AQI_RETRY:3}
  ceiling: !ENV tag:yaml.org,2002:int ${WW_AQI_CEILING:100}
  poll: !ENV tag:yaml.org,2002:int ${WW_AQI_POLL:5}
  wait_sec: !ENV tag:yaml.org,2002:int ${WW_AQI_WAIT_SEC:10}
backup:
  folder: !ENV ${WW_BACKUP_FOLDER:backup}
  file:
    enable: !ENV tag:yaml.org,2002:bool ${WW_BACKUP_ENABLE:true}
  purge:
    enable: !ENV tag:yaml.org,2002:bool ${WW_PURGE_ENABLE:true}
    img_old: !ENV tag:yaml.org,2002:int ${WW_PURGE_IMG_OLD:14}
    vid_old: !ENV tag:yaml.org,2002:int ${WW_PURGE_VID_OLD:90}
  db:
    enable: !ENV tag:yaml.org,2002:bool ${WW_DB_BACKUP_ENABLE:true}
    weekly_old: !ENV tag:yaml.org,2002:int ${WW_DB_WEEKLY_OLD:35}
camera:
  enable: !ENV tag:yaml.org,2002:bool ${WW_CAM_ENABLE:true}
  folder: !ENV ${WW_CAM_FOLDER:pix}
  lux_limit: !ENV tag:yaml.org,2002:int ${WW_CAM_LUX_LIMIT:0}
  exposure_time: !ENV tag:yaml.org,2002:int ${WW_CAM_EXP_TIME:5}
  analogue_gain: !ENV tag:yaml.org,2002:int ${WW_CAM_ISO_GAIN:10}
  extension: !ENV ${WW_CAM_FILE_EXT:.jpg}
  tuning:
    enable: !ENV tag:yaml.org,2002:bool ${WW_CAM_TUNE_ENABLE:true}
    file: !ENV ${WW_CAM_TUNE_FILE:ov5647.json}
  lens:
    make: !ENV ${WW_CAM_LENS_MAKE:Arducam}
    model: !ENV ${WW_CAM_LENS_MODEL:120 Degree Wide Angle M12}
# dashboard app
dashboard:
  # listen host
  host: !ENV ${WW_DASH_HOST:0.0.0.0}
  # listen port
  port: !ENV tag:yaml.org,2002:int ${WW_DASH_PORT:8000}
  debug: !ENV tag:yaml.org,2002:bool ${WW_DASH_DEBUG:false}
  salt_key: !ENV ${WW_DASH_SALT_KEY}
database:
  dialect: !ENV ${WW_DB_DIALECT:mariadb}
  driver: !ENV ${WW_DB_DRIVER:mariadbconnector}
  host: !ENV ${WW_DB_HOST:127.0.0.1}
  port: !ENV tag:yaml.org,2002:int ${WW_PORT:3306}
  name: !ENV ${WW_DB_NAME:weather}
  username: !ENV ${WW_DB_USERNAME}
  password: !ENV ${WW_DB_PASSWORD}
  production: !ENV tag:yaml.org,2002:bool ${WW_DB_PROD:true}
  pool:
    size: 3
    overflow: 3
email:
  enable: !ENV tag:yaml.org,2002:bool ${WW_EMAIL_ENABLE:true}
  smtp_host: !ENV ${WW_EMAIL_SMTP_HOST:smtp.gmail.com}
  smtp_port: !ENV tag:yaml.org,2002:int ${WW_EMAIL_SMTP_PORT:465}
  username: !ENV ${WW_EMAIL_USERNAME}
  password: !ENV ${WW_EMAIL_PASSWORD}
  from_email: !ENV ${WW_EMAIL_FROM}
  to_email: !ENV ${WW_EMAIL_TO}
gps:
  enable: !ENV tag:yaml.org,2002:bool ${WW_GPS_ENABLE:true}
  serial_dev: !ENV ${WW_GPS_SER_DEV:/dev/ttyUSB0}
  baud_rate: !ENV tag:yaml.org,2002:int ${WW_GPS_SER_BAUD:9600}
  init_timeout: !ENV tag:yaml.org,2002:int ${WW_GPS_INIT_TIMEOUT:30}
scheduler:
  aqi:
    # air quality sensor interval
    interval: !ENV tag:yaml.org,2002:int ${WW_AQI_INTERVAL:15}
  camera:
    # camera pic interval should not be < 5. can eat up disk space
    interval: !ENV tag:yaml.org,2002:int ${WW_CAMERA_INTERVAL:5}
  db_backup:
    hour: !ENV tag:yaml.org,2002:int ${WW_FILE_BACKUP_HOUR:3}
  file_backup:
    hour: !ENV tag:yaml.org,2002:int ${WW_FILE_BACKUP_HOUR:2}
  pimetrics:
    # system metrics polling for looking for resource issues
    interval: !ENV tag:yaml.org,2002:int ${WW_PIMETRICS_INTERVAL:10}
  sensor:
    # sensor polling interval should not be < 5
    interval: !ENV tag:yaml.org,2002:int ${WW_SENSOR_INTERVAL:5}
  timelapse:
    hour: !ENV tag:yaml.org,2002:int ${WW_TIMELAPSE_HOUR:1}
  weather_undergound:
    interval: !ENV tag:yaml.org,2002:int ${WW_WU_INTERVAL:10}
sdr:
  reader:
    # this is the total time the reader will poll if not all sensors are read
    timeout: !ENV tag:yaml.org,2002:int ${WW_SENSOR_READ_TIMEOUT:280}
  sensors:
    # doing device reset of outdoor sensor will change the id
    # device is the
    - name: outdoor
      # rtl_433 model (might not match actual sensor)
      model: Cotech-367959
      id: !ENV tag:yaml.org,2002:int ${WW_OUT_SENSOR_ID:189}
      # class that will process the data from raw json
      dataClass: OutdoorData
      # rtl_433 device id
      device: 153
    - name: indoor_3dfloor
      model: Ambientweather-F007TH
      id: 169
      channel: 2
      dataClass: IndoorData
      device: 20
    - name: indoor_basement
      model: Ambientweather-F007TH
      id: 10
      channel: 3
      dataClass: IndoorData
      device: 20
  ignores: # extraneous sensors that are not used
    - name: unknown_outdoor
      model: Cotech-367959
      dataClass: OutdoorData
      id: 181
      device: 153

timelapse:
  enable: !ENV tag:yaml.org,2002:bool ${WW_TIMELAPSE_ENABLE:true}
  folder: !ENV ${WW_TIMELAPSE_FOLDER:vid}
  extension: !ENV ${WW_CAM_TIMELAPSE_EXT:.mp4}
  fps: !ENV tag:yaml.org,2002:int ${WW_CAM_TIMELAPSE_FPS:10}
  codec: !ENV ${WW_CAM_TIMELAPSE_CODEC:avc1}
weather_undergound:
  enable: !ENV tag:yaml.org,2002:bool ${WW_WU_ENABLE:true}
  retries: !ENV tag:yaml.org,2002:int ${WW_WU_RETRIES:5}
  station_id: !ENV ${WW_WU_STATION_ID}
  station_key: !ENV ${WW_WU_STATION_KEY}
  api_key: !ENV ${WW_WU_API_KEY}
  indoor_channel: !ENV tag:yaml.org,2002:int ${WW_WU_INDOOR_CHANNEL:2}
