CREATE TABLE `outdoor_sensor` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `read_time` timestamp NOT NULL,
	`battery_ok` bit(1) NOT NULL,
	`model` VARCHAR(64) NOT NULL,
    `sensor_id` SMALLINT UNSIGNED NOT NULL,
    `temperature_f` DECIMAL(5,2) NOT NULL,
    `humidity` TINYINT UNSIGNED NOT NULL,
    `rain_mm` DECIMAL(7,3) NOT NULL,
    `wind_avg_m_s` DECIMAL(5,3) NOT NULL,
    `wind_max_m_s` DECIMAL(5,3) NOT NULL,
    `wind_dir_deg` SMALLINT UNSIGNED NOT NULL,
    `light_lux` TINYINT UNSIGNED NOT NULL,
    `uv` DECIMAL(5,3) NOT NULL,
	`mic` CHAR(3) NOT NULL,
	`mod` CHAR(3) NOT NULL,
    `freq` DECIMAL(6,3) NOT NULL,
    `snr` DECIMAL(6,3) NOT NULL,
    `noise` DECIMAL(6,3) NOT NULL,
    `raw` JSON NOT NULL COMMENT 'the raw json record', 
	PRIMARY KEY (`id`),
	UNIQUE KEY unique_sensor (read_time, model, sensor_id),
    KEY `read_time_idx` (`read_time`),
    KEY `sensor_id_idx` (`sensor_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `indoor_sensor` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `read_time` timestamp NOT NULL,
	`battery_ok` bit(1) NOT NULL,
	`model` VARCHAR(128) NOT NULL,
    `sensor_id` SMALLINT UNSIGNED NOT NULL,
    `channel` SMALLINT UNSIGNED NOT NULL,
    `temperature_f` DECIMAL(5,2) NOT NULL,
    `humidity` TINYINT UNSIGNED NOT NULL,
	`mic` CHAR(3) NOT NULL,
	`mod` CHAR(3) NOT NULL,
    `freq` DECIMAL(6,3) NOT NULL,
    `snr` DECIMAL(6,3) NOT NULL,
    `noise` DECIMAL(6,3) NOT NULL,
    `raw` JSON NOT NULL COMMENT 'the raw json record', 
	PRIMARY KEY (`id`),
	UNIQUE KEY unique_sensor (read_time, model, sensor_id, channel),
    KEY `read_time_idx` (`read_time`),
    KEY `sensor_id_channel_idx` (`sensor_id`,`channel`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;