CREATE TABLE `light_sensor` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `read_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `lux` DECIMAL(8,2) NOT NULL,
    `visible` INT UNSIGNED NOT NULL,
    `infrared` INT UNSIGNED NOT NULL,
    `full_spectrum` INT UNSIGNED NOT NULL,
    `ir_visible_luminosity` INT UNSIGNED NOT NULL,
    `ir_only` INT UNSIGNED NOT NULL,
	  PRIMARY KEY (`id`, `read_time`),
	  UNIQUE KEY light_unique_sensor (read_time)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4
  PARTITION BY RANGE( UNIX_TIMESTAMP(read_time) ) (
    PARTITION p2026 VALUES LESS THAN (UNIX_TIMESTAMP('2027-01-01')),
    PARTITION p2027 VALUES LESS THAN (UNIX_TIMESTAMP('2028-01-01')),
    PARTITION p2028 VALUES LESS THAN (UNIX_TIMESTAMP('2029-01-01')),
    PARTITION p2029 VALUES LESS THAN (UNIX_TIMESTAMP('2030-01-01')),
    PARTITION p2030 VALUES LESS THAN (UNIX_TIMESTAMP('2031-01-01')),
    PARTITION p2031 VALUES LESS THAN (UNIX_TIMESTAMP('2032-01-01')),
    PARTITION p2032 VALUES LESS THAN (UNIX_TIMESTAMP('2033-01-01')),
    PARTITION p2033 VALUES LESS THAN (UNIX_TIMESTAMP('2034-01-01')),
    PARTITION p2034 VALUES LESS THAN (UNIX_TIMESTAMP('2035-01-01')),
    PARTITION p2035 VALUES LESS THAN (UNIX_TIMESTAMP('2036-01-01')),
    PARTITION p2036 VALUES LESS THAN (UNIX_TIMESTAMP('2037-01-01')),
    PARTITION future VALUES LESS THAN MAXVALUE
  );